matomou/urls.py
from django.urls import path

from . import views

app_name = "matomou"
urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about_me, name="about"),
    path("create", views.create_entry, name="create"), 
    path("makelist", views.create_video_list, name="create_video_list"),
    path("video/<int:vdid>", views.video_detail, name="video_detail"), 
    path("list/<int:listid>", views.video_list, name="video_list"), 
    path("list/<int:listid>/edit/<int:vdid>", views.edit_list_entry, name="edit_list_entry"),
    path("list/<int:listid>/editlist", views.edit_video_list, name="edit_video_list"),
    path("api/makelist", views.call_create_video_list, name="call_create_video_list"),
    path("api/create", views.call_create_entry, name="call_create"), 
    path("api/list/<int:listid>/add", views.call_add_to_list, name="call_add_to_list"),
    path("api/list/<int:listid>/editlist", views.call_edit_video_list, name="call_edit_video_list"),
    path("api/list/<int:listid>/remove/<int:vdid>", views.call_remove_from_list, name="call_remove_from_list"),
    path("api/list/<int:listid>/edit/<int:vdid>", views.call_edit_list_entry, name="call_edit_list_entry"),


    path("api/bvproxy", views.api_bvid_proxy, name="api_bvproxy")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("matomou.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('register/', include("accounts.urls"))
]

matomou/models.py
from django.db import models
from django.contrib.auth.models import User

from .utils import get_video_site_and_id

class VideoList(models.Model):
    # A collection of videos, each entry containing:
    #  - A video ID;
    #  - A display coordinate (x, y, z); only x is actually used. 
    #  - A write-up. Markdown Supported?
    # And Metadata for the list itself:
    #  - owner_id: who owns this repo. 
    #  - public_level: The larger the number, the less people can view it;
    #    - 0: public
    #    - 1: login
    #    - 2: follower
    #    - 3: friends
    #    - 4: private
    #  - List name
    #  - List Description
    #  - List Thumbnail? Maybe not
    #  - List created_at
    #  - List updated_at

    name = models.CharField(max_length=250)
    description = models.TextField(blank=True, max_length=20000)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="video_lists")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    public_level = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Creator(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(max_length=20000, blank=True)
    
    bilibili_id = models.CharField(max_length=100, blank=True)
    youtube_id = models.CharField(max_length=100, blank=True)
    niconico_id = models.CharField(max_length=100, blank=True)

    homepage_url = models.URLField(max_length=250, blank=True)
    twitter_url = models.URLField(max_length=250, blank=True)
    weibo_url = models.URLField(max_length=250, blank=True)

    name_translations = models.TextField(max_length=1000, blank=True)
    external_links = models.TextField(max_length=1000, blank=True)

    avatar_url = models.URLField(max_length=250, blank=True)


class VideoEntry(models.Model):
    # Video Info
    video_title = models.CharField(max_length=250)
    video_title_translation = models.CharField(max_length=20000, blank=True)
    video_uploaded_at = models.DateTimeField("uploaded at")
    video_uploader_name = models.CharField(max_length=250)
    video_uploader_id = models.IntegerField()

    # Link to video
    main_url = models.URLField(max_length=250)
    bilibili_id = models.CharField(max_length=40, blank=True)
    youtube_id = models.CharField(max_length=40, blank=True)
    niconico_id = models.CharField(max_length=40, blank=True)

    # Details about the entry
    entry_created_at = models.DateTimeField("entry created at")
    contributor_id = models.IntegerField()

    # Extra information, user-transcribed
    video_description = models.CharField(max_length=20000, blank=True)
    video_credit = models.CharField(max_length=20000, blank=True)

    # Assistive Links - Thumbnail URL
    bilibili_thumbnail_link = models.URLField(max_length=250, blank=True)
    niconico_thumbnail_link = models.URLField(max_length=250, blank=True)
    youtube_thumbnail_link  = models.URLField(max_length=250, blank=True)

    # Tag
    nsfw = models.BooleanField(default=False)

    # Contributor and Uploader ForeignKey
    contributed_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="contributed_entries", null=True)
    uploaded_by = models.ForeignKey(Creator, on_delete=models.CASCADE, related_name="uploaded_entries", null=True)

    def __str__(self):
        return self.video_title
    
    @classmethod
    def find_video(cls, url):
        site, video_id = get_video_site_and_id(url)
        if not site or not video_id:
            return None
        if site == "youtube":
            return cls.objects.get(youtube_id=video_id)
        elif site == "bilibili":
            return cls.objects.get(bilibili_id=video_id)
        return None

class VideoListEntry(models.Model):
    video_list = models.ForeignKey(VideoList, on_delete=models.CASCADE, related_name="entries")
    
    video = models.ForeignKey(VideoEntry, on_delete=models.CASCADE, related_name="related_list_entries")
    order_x = models.IntegerField(default=0)
    order_y = models.IntegerField(default=0)
    order_z = models.IntegerField(default=0)
    writeup = models.TextField(blank=True, max_length=10000)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.video_list}({self.video})"



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar_url = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

matomou/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.contrib.auth.decorators import login_required

from datetime import datetime

from .models import VideoEntry, VideoList, VideoListEntry
from .utils import get_youtube_video_details, get_youtube_video_id, get_bilibili_video_id, get_bilibili_video_details

from enum import Enum


class CreateEntryCode(Enum):
    SUCCESS = 0
    BAD_URL = 1
    DUPLICATE_UPLOAD = 2
    REMOTE_FAILED = 3
    UNSUPPORTED_URL = 4

def index(request):

    listed_video_entries = VideoEntry.objects.all().order_by('-id')[:10]   # TODO: is this the most efficient SQL query?

    # Clean up data before sent as context to render template.
    cleaned_video_entries = []
    for entry in listed_video_entries:
        cleaned_video_entries.append(
            {
                "id": entry.id, 
                "video_title": entry.video_title, 
                "video_uploader_name": entry.video_uploader_name, 
                "youtube_id": entry.youtube_id,
                "bilibili_id": entry.bilibili_id,
                "main_url": entry.main_url, 
                "thumbnail_url": f"https://i.ytimg.com/vi/{entry.youtube_id}/hqdefault.jpg" if "youtube" in entry.main_url else entry.bilibili_thumbnail_link,
                "url_site": "youtube" if "youtube" in entry.main_url else "bilibili" if "bilibili" in entry.main_url else "niconico"
            }
        )
    
    # Create Video lists
    listed_video_lists = VideoList.objects.all().order_by('-id')[:10]  # TODO: is this the most efficient SQL query?

    # Clean Up
    cleaned_video_lists = []
    for vlist in listed_video_lists:
        list_entries = vlist.entries.all()    # TODO: This may cost some time!
        if not list_entries:
            continue
        lentry = list_entries[0]
        cleaned_video_lists.append(
            {
                "id": vlist.id, 
                "list_name": vlist.name, 
                "thumbnail_url": f"https://i.ytimg.com/vi/{lentry.video.youtube_id}/hqdefault.jpg" if "youtube" in lentry.video.main_url else lentry.video.bilibili_thumbnail_link
            }
        )

    context = {"video_entries": cleaned_video_entries, "video_lists": cleaned_video_lists}
    return render(request, "matomou/index.html", context)


def video_detail(request, vdid : int):
    try:
        entry = VideoEntry.objects.get(id=vdid)
    except Exception as e:
        return HttpResponse("Bad Request", status_code=400)
    if not entry:
        return HttpResponse("Bad Request", status_code=400)
    video = {
        "thumbnail_url": f"https://i.ytimg.com/vi/{entry.youtube_id}/hqdefault.jpg" if "youtube" in entry.main_url else entry.bilibili_thumbnail_link, 
        "video_title": entry.video_title, 
        "video_uploader_name": entry.video_uploader_name, 
        "main_url": entry.main_url, 
        "youtube_id": entry.youtube_id, 
        "bilibili_id": entry.bilibili_id
    }

    return render(request, "matomou/video_detail.html", {"video_entry": video})


def create_video_list(request):
    return render(request, "matomou/create_video_list.html")


def call_create_video_list(request):
    if request.method != "POST":
        return HttpResponse("Bad Request", status=400)
    
    list_name = request.POST.get("list_name")
    list_description = request.POST.get("list_description")
    public_level = request.POST.get("public_level")

    if not list_name or not list_description:
        return HttpResponse("No Input, bad request", status=400)
    

    vlist = VideoList.objects.create(
        name=list_name, 
        description=list_description, 
        owner=request.user, 
        public_level=public_level
    )

    return redirect("matomou:video_list", listid=vlist.id)

@login_required
def edit_video_list(request, listid : int):
    vlist = VideoList.objects.get(id=listid)
    if not vlist:
        return Http404()
    context = {
        "list_id": listid, 
        "list_description": vlist.description, 
        "list_name": vlist.name, 
        "public_level": vlist.public_level
    }
    return render(request, "matomou/edit_video_list.html", context=context)

@login_required
def call_edit_video_list(request, listid : int):
    if request.method != "POST":
        return HttpResponse("Bad Request", status=400)
    
    list_name = request.POST.get("list_name")
    list_description = request.POST.get("list_description")
    public_level = request.POST.get("public_level")

    if not list_name or not list_description:
        return HttpResponse("No Input, bad request", status=400)
    
    vlist = VideoList.objects.get(id=listid)
    if not vlist:
        return Http404()
    
    if vlist.owner != request.user:
        return HttpResponse("Access denied! User not owner of the List", status=403)

    vlist.name = list_name
    vlist.description = list_description
    vlist.public_level = public_level
    vlist.save()

    return redirect("matomou:video_list", listid=vlist.id)






def video_list(request, listid: int):
    thelist = VideoList.objects.get(id=listid)
    if not thelist:
        return HttpResponse("Bad Request", status=400)
    listed_video_list_entries = thelist.entries.all().order_by('order_x')

    # Clean up data before sent as context to render template.
    cleaned_video_entries = []
    for list_entry in listed_video_list_entries:
        entry = list_entry.video
        cleaned_video_entries.append(
            {
                "id": entry.id, 
                "video_title": entry.video_title, 
                "video_uploader_name": entry.video_uploader_name, 
                "writeup": list_entry.writeup, 
                "order": list_entry.order_x, 
                "youtube_id": entry.youtube_id,
                "bilibili_id": entry.bilibili_id,
                "main_url": entry.main_url, 
                "thumbnail_url": f"https://i.ytimg.com/vi/{entry.youtube_id}/hqdefault.jpg" if "youtube" in entry.main_url else entry.bilibili_thumbnail_link,
                "url_site": "youtube" if "youtube" in entry.main_url else "bilibili" if "bilibili" in entry.main_url else "niconico"
            }
        )

    context = {
        "video_entries": cleaned_video_entries, 
        "list_id": thelist.id,
        "list_name": thelist.name, 
        "list_description": thelist.description
    }

    return render(request, "matomou/video_list.html", context)
    

@login_required
def create_entry(request):
    return render(request, "matomou/create_entry.html")

@login_required
def call_create_entry(request):
    # Expected Response:
    # <QueryDict: {'csrfmiddlewaretoken': ['<--token-->'], 'video_url': ['https://www.youtube.com/watch?v=ABCDEFGHIJK']}>
    video_url = request.POST.get("video_url")
    if not video_url:
        return HttpResponse("Parsing Error: Received URL is empty.", status=400)
    video_url : str = video_url.strip()
    video_url = video_url.replace("http://", "")
    video_url = video_url.replace("https://", "")

    if "youtube.com/" in video_url:
        code = _create_youtube_entry(video_url)
    elif "bilibili.com/" in video_url:
        code = _create_bilibili_entry(video_url)
    else:
        code = CreateEntryCode.UNSUPPORTED_URL
    
    match code:
        case CreateEntryCode.SUCCESS:
            return HttpResponse("Success!")
        case CreateEntryCode.UNSUPPORTED_URL:
            return HttpResponse("Site is not supported yet!", status=400)
        case CreateEntryCode.BAD_URL:
            return HttpResponse("URL cannot be parsed!", status=400)
        case CreateEntryCode.REMOTE_FAILED:
            return HttpResponse("Failed to retrieve video data from remote site!", status=400)
        case CreateEntryCode.DUPLICATE_UPLOAD:
            return HttpResponse("The video has been uploaded!")

@login_required
def add_to_list(request, vlist_id : int):
    context = {"video_list_id": vlist_id}
    return render(request, "matomou/create_entry.html")

@login_required
def call_add_to_list(request, listid : int):
    video_url = request.POST.get("video_url")
    # --- vlist_id = request.POST.get("video_list_id")
    if not video_url or not listid:
        return HttpResponse("Parsing Error: Received URL is empty.", status=400)
    
    video_url : str = video_url.strip()
    video_url = video_url.replace("http://", "")
    video_url = video_url.replace("https://", "")

    if "youtube.com/" in video_url:
        code = _create_youtube_entry(video_url)
    elif "bilibili.com/" in video_url:
        code = _create_bilibili_entry(video_url)
    else:
        code = CreateEntryCode.UNSUPPORTED_URL
    
    if code not in (CreateEntryCode.DUPLICATE_UPLOAD, CreateEntryCode.SUCCESS):
        return HttpResponse("Creation Failed!!")
    
    try:
        video = VideoEntry.find_video(video_url)
        vlist = VideoList.objects.get(id=listid)
    except Exception as e:
        print(e)
        return HttpResponse("Unknown video / video list!", status=400)
    
    VideoListEntry.objects.create(
        video=video, 
        video_list=vlist
    )
    return redirect("matomou:video_list", listid=listid)

@login_required
def call_remove_from_list(request, listid : int, vdid : int):
    if request.method != "POST":
        return HttpResponse("Invalid request method: POST required", status=400)
    
    query = VideoListEntry.objects.filter(video_list_id=listid, video_id=vdid)
    if not query:
        return HttpResponse("No entry matches conditions.")
    list_entry = query.first()
    list_entry.delete()

    return HttpResponse("Success!")

@login_required
def edit_list_entry(request, listid : int, vdid : int):
    vlentry = VideoListEntry.objects.filter(video_id=vdid, video_list_id=listid).first()
    if not vlentry:
        return HttpResponse("Video List Entry deos not exist", status=400)
    
    writeup = vlentry.writeup
    context = {
        "list_id": listid, 

matomou/templates/matomou/create_entry.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Matomou Site alpha-0.0.1</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">


        <!-- Custom CSS Style -->
        <link href="{% static 'matomou/css/primary.css' %}" rel="stylesheet">
        <!-- Extra CSS Style -->
        <style>
            /* None at the moment */
        </style>
    </head>
    <body>
        <!-- Navbar -->
        {% include 'matomou/navbar.html' %}
        <!-- Main Canvas -->
        <!-- Preview -->
        {% comment %} <div id="preview-container" class="m-4 text-center vh-60">
            <img src="{% static 'matomou/doragon.png' %}" id="video-thumbnail" class="thumbnail" alt="Video Thumbnail">
            <div id="video-title" class="subtitle">快速创建</div>
            <div id="video-author-name" class="author-name">请在下方输入视频URL (YouTube)</div>
        </div> {% endcomment %}

        <div class="container">
            {% include 'matomou/preview_info.html' %}

            <!-- Form Box -->
            <div class="d-flex justify-content-center align-items-center vh-40">
                <form method="post" action={% url 'matomou:call_create' %} class="form-group">
                    {% csrf_token %}
                    <div class="d-flex justify-content-center">
                        <input type="text" name="video_url" id="video_url" placeholder="输入URL" class="form-control m-2" required>
                        <input type="submit" class="btn btn-primary m-2" value="提交" id="submit_button">
                    </div>
                </form>
            </div>
        </div>

    <!-- Bootstrap Script-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- Preview Script -->
    <script>
        let timeoutId;
        // Event listener for the input box
        document.getElementById("video_url").addEventListener("input", function() {
            // Clear any previous timeout to reset the timer
            clearTimeout(timeoutId);

            const urlInput = document.getElementById("video_url").value;
            const videoId = extractVideoId(urlInput);
            if (videoId) {
                timeoutId = setTimeout(() => {
                    fetchVideoDetails(videoId);
                }, 500); 
            }
        });

    </script>


</body>
</html>

matomou/templates/matomou/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'matomou:index' %}">
            Matomō a1119
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'matomou:create_video_list' %}">创建列表</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'matomou:create' %}">添加视频</a></li>
            </ul>
        </div>
    </div>
</nav>

matomou/templates/matomou/video_list.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Matomou Site alpha-0.0.1</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Custom CSS Style-->
        <link href="{% static 'matomou/css/primary.css' %}" rel="stylesheet">
        <link href="{% static 'matomoucss/video_list.css' %}" rel="stylesheet" type='text/css'>
    </head>
    <body>
        <!-- Navbar -->
        {% include "matomou/navbar.html" %}
        <!-- Banner -->

        <!-- Main Canvas -->
        <div class="container">
            <div class="col-md-10 offset-md-1">
                <!-- List description section -->
                 <div class="video-list-description">
                    <h3 class="m-2" style="border-bottom: 1px solid #ccc;">{{ list_name }}</h3>
                    <div class="m-3 justify-content-center">{{ list_description }}</div>
                    <div class="d-flex m-2">
                        <button type="button" data-bs-toggle="modal" data-bs-target="#AddVideo" class="btn btn-primary ms-2 me-2">添加视频</button>
                        <a href="{% url 'matomou:edit_video_list' list_id %}" class="btn btn-primary ms-2 me-2">编辑列表信息</a>
                    </div>
                </div>
                <!-- Actual list section -->
                <div class="overflow-auto d-flex justify-content-left align-items-center" style="flex-wrap: wrap;">
                    {% if video_entries %}
                        {% for entry in video_entries %}
                            <!-- Video Thumbnail -->
                            <div class="col-12 col-sm-6 col-md-6 col-lg-3 d-flex justify-content-center">
                                <div data-bs-toggle="modal" data-bs-target="#EntryModal{{entry.id}}" style="cursor: pointer;" class="position-relative d-block overflow-hidden shadow m-3 thumbnail-container">
                                    <div class="img-fluid" style="width: 100%; height: 100%; max-width: 500px; aspect-ratio: 16 / 9; object-fit: cover; text-align: center;">
                                        <img src="{{ entry.thumbnail_url }}" alt="Thumbnail" style="width: 100%; height: 100%; object-fit: cover; ">
                                        <div class="subtitle-overlay">{{entry.video_title}}</div>
                                        <div class="d-flex justify-content-right" style="position: absolute; right: 8%; top: 10%;">
                                            {% if entry.youtube_id %}
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="youtube-button ms-1">
                                                <a href="https://www.youtube.com/watch?v={{ entry.youtube_id }}" onclick="event.stopPropagation();">
                                                    <rect width="24" height="24" fill="transparent"/>
                                                    <path class="youtube-button-path" fill="#FFFFFF" d="M23.498 6.186a2.946 2.946 0 0 0-2.072-2.082C19.409 3.553 12 3.553 12 3.553s-7.408 0-9.426.552A2.946 2.946 0 0 0 .502 6.186C0 8.204 0 12 0 12s0 3.796.502 5.814a2.946 2.946 0 0 0 2.072 2.082c2.018.552 9.426.552 9.426.552s7.409 0 9.426-.552a2.946 2.946 0 0 0 2.072-2.082C24 15.796 24 12 24 12s0-3.796-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/>
                                                </a>
                                            </svg>
                                            {% endif %}
                                            {% if entry.bilibili_id %}
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="youtube-button ms-1">
                                                <a href="https://www.bilibili.com/video/{{ entry.bilibili_id }}" onclick="event.stopPropagation();">
                                                    <rect width="24" height="24" fill="transparent"/>
                                                    <path class="youtube-button-path" fill="#FFFFFF" d="M18.223 3.086a1.25 1.25 0 0 1 0 1.768L17.08 5.996h1.17A3.75 3.75 0 0 1 22 9.747v7.5a3.75 3.75 0 0 1-3.75 3.75H5.75A3.75 3.75 0 0 1 2 17.247v-7.5a3.75 3.75 0 0 1 3.75-3.75h1.166L5.775 4.855a1.25 1.25 0 1 1 1.767-1.768l2.652 2.652c.079.079.145.165.198.257h3.213c.053-.092.12-.18.199-.258l2.651-2.652a1.25 1.25 0 0 1 1.768 0zm.027 5.42H5.75a1.25 1.25 0 0 0-1.247 1.157l-.003.094v7.5c0 .659.51 1.199 1.157 1.246l.093.004h12.5a1.25 1.25 0 0 0 1.247-1.157l.003-.093v-7.5c0-.69-.56-1.25-1.25-1.25zm-10 2.5c.69 0 1.25.56 1.25 1.25v1.25a1.25 1.25 0 1 1-2.5 0v-1.25c0-.69.56-1.25 1.25-1.25zm7.5 0c.69 0 1.25.56 1.25 1.25v1.25a1.25 1.25 0 1 1-2.5 0v-1.25c0-.69.56-1.25 1.25-1.25z"/>
                                                </a>
                                            </svg>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>      
                            </div>
                            <!-- Modal -->
                            <div class="modal fade" id="EntryModal{{entry.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Modal Title</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            {{ entry.writeup }}
                                        </div>
                                        <div class="modal-footer">
                                            <a href="{% url 'matomou:edit_list_entry' list_id entry.id %}" type="button" class="btn btn-primary">
                                                <i class="bi bi-pencil"></i> Edit
                                            </a>
                                            <form method="post" action={% url 'matomou:call_remove_from_list' list_id entry.id %}>
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-danger">
                                                    <i class="bi bi-trash"></i> Remove
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        No Entries are available.
                    {% endif %}
                </div>

                <!-- Add Video Modal -->

                <div class="modal fade" id="AddVideo" tabindex="-1" aria-labelledby="AddVideoLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="AddVideoLabel">添加新视频</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            {% include "matomou/preview_info.html" %}
                            <form method="post" action={% url 'matomou:call_add_to_list' list_id %} class="form-group">
                                {% csrf_token %}
                                <div class="modal-body">
                                    <input type="text" name="video_url" id="video_url" placeholder="输入URL" class="form-control m-2" required></input>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                                    <button type="submit" class="btn btn-primary">添加视频</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
        <!-- Bootstrap Script-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script>
            let timeoutId;
            // Event listener for the input box
            document.getElementById("video_url").addEventListener("input", function() {
                // Clear any previous timeout to reset the timer
                clearTimeout(timeoutId);

                const urlInput = document.getElementById("video_url").value;
                const videoId = extractVideoId(urlInput);
                if (videoId) {
                    timeoutId = setTimeout(() => {
                        fetchVideoDetails(videoId);
                    }, 500); 
                }
            });
        </script>
    
    
    </body>
</html>